FROM node:14.15.3
WORKDIR /usr/src/luck-ui-2
COPY package.json ./
RUN yarn install
COPY . .
ARG CMS_USERNAME
ARG CMS_PASSWORD
ARG CLIENT_URL
ARG TRACKING_ID
ARG SHOULD_SHOW_DRAFT
ARG VIRTUAL_HOST
ENV CMS_USERNAME=$CMS_USERNAME
ENV CMS_PASSWORD=$CMS_PASSWORD
ENV CLIENT_URL=$CLIENT_URL
ENV TRACKING_ID=$TRACKING_ID
ENV SHOULD_SHOW_DRAFT=$SHOULD_SHOW_DRAFT
ENV VIRTUAL_HOST=$VIRTUAL_HOST
RUN yarn run build
ENV PORT 3000
EXPOSE 3000
CMD ["yarn", "start"]
