FROM node:10-alpine
WORKDIR /usr/src/luck-ui-2
COPY package.json ./
RUN yarn install
COPY . .
ARG APPOLO_CLIENT_TOKEN
ARG CLIENT_URL
ARG TRACKING_ID
ENV APPOLO_CLIENT_TOKEN=$APPOLO_CLIENT_TOKEN
ENV CLIENT_URL=$CLIENT_URL
ENV TRACKING_ID=$TRACKING_ID
RUN yarn run build
ENV PORT 3000
EXPOSE 3000
CMD ["yarn", "start"]
